root: true
env:
  browser: true
extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - '**/typings/**/*.ts'
  - 'dist/*'
  - 'test/*'
rules: {
  'no-case-declarations': 0,
  '@typescript-eslint/no-non-null-assertion': 0,
  '@typescript-eslint/no-explicit-any': 0,
  '@typescript-eslint/ban-types': 0
}
